In [20]:
import pandas as pd
import numpy as np

In [21]:
meusDados= np.matrix('1, 2, 3; 4, 5, 6; 7, 8, 9; 10, 11, 12')
meusDados

matrix([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]])

In [22]:
meuDf = pd.DataFrame(meusDados)

In [23]:
type(meuDf)

pandas.core.frame.DataFrame

In [24]:
indice = ['Linha ' + str(i) for i in range(4)]

In [25]:
colunas = ['Coluna ' + str(i) for i in range(3)]

In [26]:
df2 = pd.DataFrame(data= meusDados, index= indice, columns= colunas)
df2

Coluna 0  Coluna 1  Coluna 2
Linha 0         1         2         3
Linha 1         4         5         6
Linha 2         7         8         9
Linha 3        10        11        12

In [27]:
df2 = pd.DataFrame(meusDados, indice, colunas)

In [15]:
df3 = {'Coluna0': {'Linha0': 1, 'Linha1': 4, 'Linha2': 7},
       'Coluna1': {'Linha0': 2, 'Linha1': 5, 'Linha2': 8},
       'Coluna2': {'Linha0': 3, 'Linha1': 6, 'Linha2': 9}}

In [29]:
df3 = pd.DataFrame(df3)
df3

Coluna0  Coluna1  Coluna2
Linha0        1        2        3
Linha1        4        5        6
Linha2        7        8        9

In [32]:
df4 = pd.concat([meuDf, df2, df3])
df4

0     1     2  Coluna 0  Coluna 1  Coluna 2  Coluna0  Coluna1  \
0         1.0   2.0   3.0       NaN       NaN       NaN      NaN      NaN   
1         4.0   5.0   6.0       NaN       NaN       NaN      NaN      NaN   
2         7.0   8.0   9.0       NaN       NaN       NaN      NaN      NaN   
3        10.0  11.0  12.0       NaN       NaN       NaN      NaN      NaN   
Linha 0   NaN   NaN   NaN       1.0       2.0       3.0      NaN      NaN   
Linha 1   NaN   NaN   NaN       4.0       5.0       6.0      NaN      NaN   
Linha 2   NaN   NaN   NaN       7.0       8.0       9.0      NaN      NaN   
Linha 3   NaN   NaN   NaN      10.0      11.0      12.0      NaN      NaN   
Linha0    NaN   NaN   NaN       NaN       NaN       NaN      1.0      2.0   
Linha1    NaN   NaN   NaN       NaN       NaN       NaN      4.0      5.0   
Linha2    NaN   NaN   NaN       NaN       NaN       NaN      7.0      8.0   

         Coluna2  
0            NaN  
1            NaN  
2            NaN  
3            NaN  
Linha 0      NaN  
Linha 1      NaN  
Linha 2      NaN  
Linha 3      NaN  
Linha0       3.0  
Linha1       6.0  
Linha2       9.0

In [33]:
df4.isnull()

0      1      2  Coluna 0  Coluna 1  Coluna 2  Coluna0  Coluna1  \
0        False  False  False      True      True      True     True     True   
1        False  False  False      True      True      True     True     True   
2        False  False  False      True      True      True     True     True   
3        False  False  False      True      True      True     True     True   
Linha 0   True   True   True     False     False     False     True     True   
Linha 1   True   True   True     False     False     False     True     True   
Linha 2   True   True   True     False     False     False     True     True   
Linha 3   True   True   True     False     False     False     True     True   
Linha0    True   True   True      True      True      True    False    False   
Linha1    True   True   True      True      True      True    False    False   
Linha2    True   True   True      True      True      True    False    False   

         Coluna2  
0           True  
1           True  
2           True  
3           True  
Linha 0     True  
Linha 1     True  
Linha 2     True  
Linha 3     True  
Linha0     False  
Linha1     False  
Linha2     False

In [34]:
df4.isnull().sum()

0           7
1           7
2           7
Coluna 0    7
Coluna 1    7
Coluna 2    7
Coluna0     8
Coluna1     8
Coluna2     8
dtype: int64

In [35]:
df5 = df4.fillna(df4.mean())
df5

0     1     2  Coluna 0  Coluna 1  Coluna 2  Coluna0  Coluna1  \
0         1.0   2.0   3.0       5.5       6.5       7.5      4.0      5.0   
1         4.0   5.0   6.0       5.5       6.5       7.5      4.0      5.0   
2         7.0   8.0   9.0       5.5       6.5       7.5      4.0      5.0   
3        10.0  11.0  12.0       5.5       6.5       7.5      4.0      5.0   
Linha 0   5.5   6.5   7.5       1.0       2.0       3.0      4.0      5.0   
Linha 1   5.5   6.5   7.5       4.0       5.0       6.0      4.0      5.0   
Linha 2   5.5   6.5   7.5       7.0       8.0       9.0      4.0      5.0   
Linha 3   5.5   6.5   7.5      10.0      11.0      12.0      4.0      5.0   
Linha0    5.5   6.5   7.5       5.5       6.5       7.5      1.0      2.0   
Linha1    5.5   6.5   7.5       5.5       6.5       7.5      4.0      5.0   
Linha2    5.5   6.5   7.5       5.5       6.5       7.5      7.0      8.0   

         Coluna2  
0            6.0  
1            6.0  
2            6.0  
3            6.0  
Linha 0      6.0  
Linha 1      6.0  
Linha 2      6.0  
Linha 3      6.0  
Linha0       3.0  
Linha1       6.0  
Linha2       9.0

In [36]:
df8 = df5.copy()

In [37]:
df4.dropna(inplace = True)
df4

Empty DataFrame
Columns: [0, 1, 2, Coluna 0, Coluna 1, Coluna 2, Coluna0, Coluna1, Coluna2]
Index: []

In [38]:
df5

0     1     2  Coluna 0  Coluna 1  Coluna 2  Coluna0  Coluna1  \
0         1.0   2.0   3.0       5.5       6.5       7.5      4.0      5.0   
1         4.0   5.0   6.0       5.5       6.5       7.5      4.0      5.0   
2         7.0   8.0   9.0       5.5       6.5       7.5      4.0      5.0   
3        10.0  11.0  12.0       5.5       6.5       7.5      4.0      5.0   
Linha 0   5.5   6.5   7.5       1.0       2.0       3.0      4.0      5.0   
Linha 1   5.5   6.5   7.5       4.0       5.0       6.0      4.0      5.0   
Linha 2   5.5   6.5   7.5       7.0       8.0       9.0      4.0      5.0   
Linha 3   5.5   6.5   7.5      10.0      11.0      12.0      4.0      5.0   
Linha0    5.5   6.5   7.5       5.5       6.5       7.5      1.0      2.0   
Linha1    5.5   6.5   7.5       5.5       6.5       7.5      4.0      5.0   
Linha2    5.5   6.5   7.5       5.5       6.5       7.5      7.0      8.0   

         Coluna2  
0            6.0  
1            6.0  
2            6.0  
3            6.0  
Linha 0      6.0  
Linha 1      6.0  
Linha 2      6.0  
Linha 3      6.0  
Linha0       3.0  
Linha1       6.0  
Linha2       9.0

In [46]:
df5.dropna(subset= [1], inplace = True)
df5

0     1     2  Coluna 0  Coluna 1  Coluna 2  Coluna0  Coluna1  \
0         1.0   2.0   3.0       5.5       6.5       7.5      4.0      5.0   
1         4.0   5.0   6.0       5.5       6.5       7.5      4.0      5.0   
2         7.0   8.0   9.0       5.5       6.5       7.5      4.0      5.0   
3        10.0  11.0  12.0       5.5       6.5       7.5      4.0      5.0   
Linha 0   5.5   6.5   7.5       1.0       2.0       3.0      4.0      5.0   
Linha 1   5.5   6.5   7.5       4.0       5.0       6.0      4.0      5.0   
Linha 2   5.5   6.5   7.5       7.0       8.0       9.0      4.0      5.0   
Linha 3   5.5   6.5   7.5      10.0      11.0      12.0      4.0      5.0   
Linha0    5.5   6.5   7.5       5.5       6.5       7.5      1.0      2.0   
Linha1    5.5   6.5   7.5       5.5       6.5       7.5      4.0      5.0   
Linha2    5.5   6.5   7.5       5.5       6.5       7.5      7.0      8.0   

         Coluna2  
0            6.0  
1            6.0  
2            6.0  
3            6.0  
Linha 0      6.0  
Linha 1      6.0  
Linha 2      6.0  
Linha 3      6.0  
Linha0       3.0  
Linha1       6.0  
Linha2       9.0

In [44]:
df6 = df5.drop(columns = ['Coluna 0'])
df6

0     1     2  Coluna 1  Coluna 2  Coluna0  Coluna1  Coluna2
0         1.0   2.0   3.0       6.5       7.5      4.0      5.0      6.0
1         4.0   5.0   6.0       6.5       7.5      4.0      5.0      6.0
2         7.0   8.0   9.0       6.5       7.5      4.0      5.0      6.0
3        10.0  11.0  12.0       6.5       7.5      4.0      5.0      6.0
Linha 0   5.5   6.5   7.5       2.0       3.0      4.0      5.0      6.0
Linha 1   5.5   6.5   7.5       5.0       6.0      4.0      5.0      6.0
Linha 2   5.5   6.5   7.5       8.0       9.0      4.0      5.0      6.0
Linha 3   5.5   6.5   7.5      11.0      12.0      4.0      5.0      6.0
Linha0    5.5   6.5   7.5       6.5       7.5      1.0      2.0      3.0
Linha1    5.5   6.5   7.5       6.5       7.5      4.0      5.0      6.0
Linha2    5.5   6.5   7.5       6.5       7.5      7.0      8.0      9.0

In [47]:
df7 = df6.drop(index = [2])
df7

0     1     2  Coluna 1  Coluna 2  Coluna0  Coluna1  Coluna2
0         1.0   2.0   3.0       6.5       7.5      4.0      5.0      6.0
1         4.0   5.0   6.0       6.5       7.5      4.0      5.0      6.0
3        10.0  11.0  12.0       6.5       7.5      4.0      5.0      6.0
Linha 0   5.5   6.5   7.5       2.0       3.0      4.0      5.0      6.0
Linha 1   5.5   6.5   7.5       5.0       6.0      4.0      5.0      6.0
Linha 2   5.5   6.5   7.5       8.0       9.0      4.0      5.0      6.0
Linha 3   5.5   6.5   7.5      11.0      12.0      4.0      5.0      6.0
Linha0    5.5   6.5   7.5       6.5       7.5      1.0      2.0      3.0
Linha1    5.5   6.5   7.5       6.5       7.5      4.0      5.0      6.0
Linha2    5.5   6.5   7.5       6.5       7.5      7.0      8.0      9.0

In [48]:
df5.Coluna2.unique()

array([6., 3., 9.])

In [49]:
df5.columns.unique()

Index([0, 1, 2, 'Coluna 0', 'Coluna 1', 'Coluna 2', 'Coluna0', 'Coluna1',
       'Coluna2'],
      dtype='object')

In [50]:
print(df5.Coluna2.unique())

[6. 3. 9.]


In [51]:
print(df5.columns.unique())

Index([0, 1, 2, 'Coluna 0', 'Coluna 1', 'Coluna 2', 'Coluna0', 'Coluna1',
       'Coluna2'],
      dtype='object')


In [52]:
print(df5.index.unique())

Index([        0,         1,         2,         3, 'Linha 0', 'Linha 1',
       'Linha 2', 'Linha 3',  'Linha0',  'Linha1',  'Linha2'],
      dtype='object')


In [54]:
df8.sort_values(by = 'Coluna 1')

0     1     2  Coluna 0  Coluna 1  Coluna 2  Coluna0  Coluna1  \
Linha 0   5.5   6.5   7.5       1.0       2.0       3.0      4.0      5.0   
Linha 1   5.5   6.5   7.5       4.0       5.0       6.0      4.0      5.0   
0         1.0   2.0   3.0       5.5       6.5       7.5      4.0      5.0   
1         4.0   5.0   6.0       5.5       6.5       7.5      4.0      5.0   
2         7.0   8.0   9.0       5.5       6.5       7.5      4.0      5.0   
3        10.0  11.0  12.0       5.5       6.5       7.5      4.0      5.0   
Linha0    5.5   6.5   7.5       5.5       6.5       7.5      1.0      2.0   
Linha1    5.5   6.5   7.5       5.5       6.5       7.5      4.0      5.0   
Linha2    5.5   6.5   7.5       5.5       6.5       7.5      7.0      8.0   
Linha 2   5.5   6.5   7.5       7.0       8.0       9.0      4.0      5.0   
Linha 3   5.5   6.5   7.5      10.0      11.0      12.0      4.0      5.0   

         Coluna2  
Linha 0      6.0  
Linha 1      6.0  
0            6.0  
1            6.0  
2            6.0  
3            6.0  
Linha0       3.0  
Linha1       6.0  
Linha2       9.0  
Linha 2      6.0  
Linha 3      6.0

In [56]:
df8.rename(columns = {'Coluna1':'COLUNA 1'}, inplace = True)
df8

0     1     2  Coluna 0  Coluna 1  Coluna 2  Coluna0  COLUNA 1  \
0         1.0   2.0   3.0       5.5       6.5       7.5      4.0       5.0   
1         4.0   5.0   6.0       5.5       6.5       7.5      4.0       5.0   
2         7.0   8.0   9.0       5.5       6.5       7.5      4.0       5.0   
3        10.0  11.0  12.0       5.5       6.5       7.5      4.0       5.0   
Linha 0   5.5   6.5   7.5       1.0       2.0       3.0      4.0       5.0   
Linha 1   5.5   6.5   7.5       4.0       5.0       6.0      4.0       5.0   
Linha 2   5.5   6.5   7.5       7.0       8.0       9.0      4.0       5.0   
Linha 3   5.5   6.5   7.5      10.0      11.0      12.0      4.0       5.0   
Linha0    5.5   6.5   7.5       5.5       6.5       7.5      1.0       2.0   
Linha1    5.5   6.5   7.5       5.5       6.5       7.5      4.0       5.0   
Linha2    5.5   6.5   7.5       5.5       6.5       7.5      7.0       8.0   

         Coluna2  
0            6.0  
1            6.0  
2            6.0  
3            6.0  
Linha 0      6.0  
Linha 1      6.0  
Linha 2      6.0  
Linha 3      6.0  
Linha0       3.0  
Linha1       6.0  
Linha2       9.0